# Generated by Django 5.0.2 on 2024-04-19 20:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='condition',
            name='limit',
            field=models.IntegerField(verbose_name='Цель'),
        ),
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время оплаты')),
                ('numberOfPeople', models.IntegerField(verbose_name='Количество людей')),
                ('cheque', models.FloatField(verbose_name='Чек(сколько оплачено)')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.event')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.userdata')),
            ],
        ),
    ]
