# Generated by Django 5.0.2 on 2024-04-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userdata_user_alter_condition_limit_inputdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='score',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество баллов'),
        ),
    ]
