# Generated by Django 5.0.2 on 2024-04-20 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_level_digitalequivalent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userachievementnotcomplate',
            name='achievementNotComplate',
        ),
        migrations.RemoveField(
            model_name='userachievementnotcomplate',
            name='user',
        ),
        migrations.AddField(
            model_name='achievement',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.event'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='limit',
            field=models.IntegerField(default=1, verbose_name='Цель'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='progress',
            field=models.IntegerField(default=0, verbose_name='Прогресс'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='requiredQuantity',
            field=models.IntegerField(default=1, verbose_name='Необходимое количество людей'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='text',
            field=models.TextField(blank=True, max_length=300, verbose_name='Текст условия'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='achievementDone',
            field=models.ManyToManyField(blank=True, to='main.achievement'),
        ),
        migrations.DeleteModel(
            name='UserAchievementDone',
        ),
        migrations.DeleteModel(
            name='UserAchievementNotComplate',
        ),
    ]
