# Generated by Django 5.0.2 on 2024-04-20 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_level_discounts_level_value_delete_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='condition',
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
    ]
