# Generated by Django 5.0.2 on 2024-04-20 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_achievement_condition_delete_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='progress',
        ),
        migrations.CreateModel(
            name='AchievementProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=1, verbose_name='Количество людей')),
                ('achievement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.achievement')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.userdata')),
            ],
        ),
    ]
