# Generated by Django 5.0.2 on 2024-04-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_achievement_progress_achievementprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='achievementDone',
        ),
        migrations.AlterField(
            model_name='achievementprogress',
            name='progress',
            field=models.IntegerField(default=0, verbose_name='Прогресс'),
        ),
    ]
