# Generated by Django 5.0.2 on 2024-04-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_userdata_achievementdone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementprogress',
            name='DoneOrNot',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
    ]
