# Generated by Django 5.0.2 on 2024-04-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_achievement_scores_achievement_addexperience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='theard_name',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Фамилия'),
        ),
    ]
