# Generated by Django 5.0.2 on 2024-04-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_userdata_email_userdata_theard_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='lvl', verbose_name='Иконка'),
        ),
    ]
