# Generated by Django 5.0.2 on 2024-04-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_level_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='сategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='lvl', verbose_name='Иконка'),
        ),
    ]
